### ISSUE TITLE
Invalid argument supplied to oneOf, expected an instance of array.

### ISSUE THREAD

**Issue by ghost** [acsant/react-native-recaptcha#2]
`PropTypes.oneOf` only accepts an array but an object is passed.

`reCaptchaType: PropTypes.oneOf(type).isRequired`

Instead, what you could do is:

`reCaptchaType: PropTypes.oneOf(Object.values(type)).isRequired`

Also, what exactly is the `url` prop for?

**Comment by EdwinJDiaz** [comment]
some follow up on this??

**Comment by acsant** [comment]
Hello! 

Sorry for being MIA for a bit. I've updated the code and the documentation to reflect the changes. I have also changed the types to `invisible` and `normal` instead since that is more intuitive. Hope this helps. You should be able to update the NPM package.
Here is a reference to the commit: 07908c9bf1f9c46d38b8e3085ee26fb962a155f0

Appreciated your feedback on this :)

Thanks,
Akash
